"""Routing, frame budget and prompt of every HeiCo-FOCUS PROCEDURE question (6,000, train + test)
match the released fixture, which was generated by the code of the challenge submission.

Needs the dataset: SURGSCOPE_DATA_ROOTS="heico=/path/to/heico-focus-vqa"
The fixture stores only hashes and window bounds (no question text, no answers).
"""
import gzip
import hashlib
import json
import os
from pathlib import Path

import pytest

from surgscope import policy
from surgscope.prompts import user_content
from surgscope.routing import route

FIXTURE = Path(__file__).parent / "golden" / "questions.v1.jsonl.gz"


def key(ds, qid, end_s, question):
    return hashlib.sha1(f"{ds}|{qid}|{end_s}|{question}".encode()).hexdigest()[:16]


def record(question, end_s, procedure_type):
    r = route(question, end_s)
    hint = user_content(question, int(r["w0"]), int(r["w1"]), procedure_type)
    return {"tier": r["tier"], "rule": r["rule"], "w0": r["w0"], "w1": r["w1"], "shrunk": r["shrunk"],
            "branch": policy.branch(question),
            "nframes": {reg: policy.nframes(question, reg) for reg in policy.REGIMES},
            "prompt": hashlib.sha1(hint.encode()).hexdigest()[:16]}


@pytest.mark.golden
def test_golden_questions():
    roots = os.environ.get("SURGSCOPE_DATA_ROOTS")
    if not roots:
        pytest.skip("set SURGSCOPE_DATA_ROOTS to run")
    import pyarrow.parquet as pq
    want = {}
    with gzip.open(FIXTURE, "rt") as f:
        for line in f:
            d = json.loads(line)
            want[d.pop("key")] = d
    n = 0
    for item in roots.split(","):
        ds, root = item.split("=", 1)
        for split in ("train", "test"):
            for r in pq.read_table(Path(root) / "data" / "procedure" / f"{split}.parquet").to_pylist():
                h, m, s = map(int, r["timestamp_end"].split(":"))
                end_s = h * 3600 + m * 60 + s
                k = key(ds, r["id"], end_s, r["question"])
                if k in want:
                    assert record(r["question"], end_s, r["procedure_type"]) == want[k], (ds, r["id"])
                    n += 1
    assert n > 0
